version: 1.5.0.{build}
image: Visual Studio 2022

configuration:
- Debug-Asan
- Release-Clang
- Release

platform:
- Win32
- x64
- ARM64

environment:
  EXPLORERPLUSPLUS_BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)

cache:
  - vcpkg_installed -> vcpkg.json
  - '%LOCALAPPDATA%\vcpkg\archives -> vcpkg.json'

matrix:
  fast_finish: true
  exclude:
    - configuration: Debug-Asan
      platform: ARM64
    - configuration: Release-Clang
      platform: Win32
    - configuration: Release-Clang
      platform: ARM64

for:
-
  branches:
    only:
      - /version-.*/

  skip_non_tags: true

-
  matrix:
    only:
      - platform: Win32

  environment:
    arch: x86

-
  matrix:
    only:
      - platform: x64

  environment:
    arch: x64

-
  matrix:
    only:
      - platform: ARM64

  environment:
    arch: arm64

init:
- pwsh: >-
    if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -match '^l10n_') {
      Write-Host 'Skipping translation branch pull request'
      Exit-AppveyorBuild
    }

install:
- cmd: >-
    git submodule init

    git submodule update

    .\Explorer++\ThirdParty\vcpkg\bootstrap-vcpkg.bat

before_build:
- pwsh: >-
    if (Test-Path env:APPVEYOR_REPO_TAG_NAME) {
      if ($env:APPVEYOR_REPO_TAG_NAME -match '-beta(-\d)?$') {
        $env:RELEASE_MODE = 'beta'
      } else {
        $env:RELEASE_MODE = 'stable'
      }
    }

build:
  project: Explorer++\Explorer++.sln
  verbosity: minimal

after_build:
- pwsh: .appveyor\after_build.ps1

test_script:
- pwsh: .appveyor\test_script.ps1