// Copyright (C) Explorer++ Project
// SPDX-License-Identifier: GPL-3.0-only
// See LICENSE in the top level directory

#pragma once

#include "ShellBrowser/FolderSettings.h"
#include "ShellBrowser/ViewModes.h"
#include "../Helper/Macros.h"
#include "../Helper/SetDefaultFileManager.h"
#include "../Helper/ShellHelper.h"
#include "../Helper/StringHelper.h"
#include <boost/signals2.hpp>

static const int DEFAULT_LISTVIEW_HOVER_TIME = 500;

enum StartupMode_t
{
	STARTUP_PREVIOUSTABS = 1,
	STARTUP_DEFAULTFOLDER = 2
};

enum InfoTipType_t
{
	INFOTIP_SYSTEM = 0,
	INFOTIP_CUSTOM = 1
};

// This saves a fair amount of boilerplate code from having to be
// written. It allows the stored value to be retrieved and updated
// (using getter and setter methods) and allows changes to be observed.
// Without something like this, getter/setter methods would need to be
// written manually. Even if they were generated by a tool, there would
// still be a lot of additional code and the observer code would also
// need to be set up on a per-variable basis.
template<typename T>
class ValueWrapper
{
public:

	using ValueUpdatedSignal = boost::signals2::signal<void(T newValue)>;

	ValueWrapper() :
		m_value()
	{

	}

	// This is designed to allow the parent Config struct to be copied
	// when necessary. None of the observers are copied, you only get a
	// copy of the data.
	ValueWrapper(const ValueWrapper &variableChange)
	{
		m_value = variableChange.get();
	}

	T get() const
	{
		return m_value;
	}

	void set(T value)
	{
		if (value != m_value)
		{
			m_value = value;
			m_valueUpdatedSignal(value);
		}
	}

	boost::signals2::connection addObserver(const typename ValueUpdatedSignal::slot_type &observer)
	{
		return m_valueUpdatedSignal.connect(observer);
	}

private:

	T m_value;
	ValueUpdatedSignal m_valueUpdatedSignal;
};

struct Config
{
	Config() :
		defaultTabDirectoryStatic(GetComputerFolderPath())
	{
		startupMode = STARTUP_PREVIOUSTABS;
		defaultTabDirectory = GetComputerFolderPath();
		showStatusBar = TRUE;
		showFolders = TRUE;
		showAddressBar = TRUE;
		showDisplayWindow = TRUE;
		showMainToolbar = TRUE;
		showBookmarksToolbar = FALSE;
		showDrivesToolbar = TRUE;
		showApplicationToolbar = FALSE;
		showTabBarAtBottom = FALSE;
		alwaysOpenNewTab = FALSE;
		openNewTabNextToCurrent = FALSE;
		lockToolbars = TRUE;
		treeViewDelayEnabled = FALSE;
		treeViewAutoExpandSelected = FALSE;
		showTaskbarThumbnails = TRUE;
		useFullRowSelect = FALSE;
		showFilePreviews = TRUE;
		extendTabControl = FALSE;
		allowMultipleInstances = TRUE;
		doubleClickTabClose = TRUE;
		useLargeToolbarIcons = FALSE;
		handleZipFiles = FALSE;
		insertSorted = TRUE;
		overwriteExistingFilesConfirmation = TRUE;
		checkBoxSelection = FALSE;
		closeMainWindowOnTabClose = TRUE;
		playNavigationSound = TRUE;
		confirmCloseTabs = FALSE;
		synchronizeTreeview = TRUE;
		displayWindowHeight = DEFAULT_DISPLAYWINDOW_HEIGHT;
		treeViewWidth = DEFAULT_TREEVIEW_WIDTH;

		replaceExplorerMode = NDefaultFileManager::REPLACEEXPLORER_NONE;

		showInfoTips = TRUE;
		infoTipType = INFOTIP_SYSTEM;

		showFullTitlePath.set(FALSE);
		showUserNameInTitleBar.set(FALSE);
		showPrivilegeLevelInTitleBar.set(FALSE);

		alwaysShowTabBar.set(TRUE);
		forceSameTabWidth.set(FALSE);

		globalFolderSettings.showExtensions = TRUE;
		globalFolderSettings.showFriendlyDates = TRUE;
		globalFolderSettings.showFolderSizes = FALSE;
		globalFolderSettings.disableFolderSizesNetworkRemovable = FALSE;
		globalFolderSettings.hideSystemFiles = FALSE;
		globalFolderSettings.hideLinkExtension = FALSE;
		globalFolderSettings.showGridlines = TRUE;
		globalFolderSettings.forceSize = FALSE;
		globalFolderSettings.sizeDisplayFormat = SIZE_FORMAT_BYTES;
		globalFolderSettings.oneClickActivate = FALSE;
		globalFolderSettings.oneClickActivateHoverTime = DEFAULT_LISTVIEW_HOVER_TIME;

		defaultFolderSettings.sortMode = SortMode::Name;
		defaultFolderSettings.viewMode = ViewMode::Icons;
		defaultFolderSettings.sortAscending = TRUE;
		defaultFolderSettings.showInGroups = FALSE;
		defaultFolderSettings.showHidden = TRUE;
		defaultFolderSettings.autoArrange = TRUE;
		defaultFolderSettings.applyFilter = FALSE;
		defaultFolderSettings.filterCaseSensitive = FALSE;
	}

	static const UINT DEFAULT_DISPLAYWINDOW_HEIGHT = 90;
	static const UINT DEFAULT_TREEVIEW_WIDTH = 208;

	StartupMode_t startupMode;
	std::wstring defaultTabDirectory;
	const std::wstring defaultTabDirectoryStatic;
	BOOL showStatusBar;
	BOOL showFolders;
	BOOL showAddressBar;
	BOOL showDisplayWindow;
	BOOL showMainToolbar;
	BOOL showBookmarksToolbar;
	BOOL showDrivesToolbar;
	BOOL showApplicationToolbar;
	BOOL showTabBarAtBottom;
	BOOL alwaysOpenNewTab;
	BOOL openNewTabNextToCurrent;
	BOOL lockToolbars;
	BOOL treeViewDelayEnabled;
	BOOL treeViewAutoExpandSelected;
	BOOL showTaskbarThumbnails;
	BOOL useFullRowSelect;
	BOOL showFilePreviews;
	BOOL extendTabControl;
	BOOL allowMultipleInstances;
	BOOL doubleClickTabClose;
	BOOL useLargeToolbarIcons;
	BOOL handleZipFiles;
	BOOL insertSorted;
	BOOL overwriteExistingFilesConfirmation;
	BOOL checkBoxSelection;
	BOOL closeMainWindowOnTabClose;
	BOOL playNavigationSound;
	BOOL confirmCloseTabs;
	BOOL synchronizeTreeview;
	LONG displayWindowHeight;
	unsigned int treeViewWidth;

	NDefaultFileManager::ReplaceExplorerModes_t replaceExplorerMode;

	BOOL showInfoTips;
	InfoTipType_t infoTipType;

	// Main window
	ValueWrapper<BOOL> showFullTitlePath;
	ValueWrapper<BOOL> showUserNameInTitleBar;
	ValueWrapper<BOOL> showPrivilegeLevelInTitleBar;

	// Tabs
	ValueWrapper<BOOL> alwaysShowTabBar;
	ValueWrapper<BOOL> forceSameTabWidth;

	// These are settings that are shared between all tabs. It's not
	// possible to adjust them on a per-tab basis.
	GlobalFolderSettings globalFolderSettings;

	FolderSettings defaultFolderSettings;

private:

	static std::wstring GetComputerFolderPath()
	{
		// It's assumed here that this won't fail.
		TCHAR computerPath[MAX_PATH];
		GetCsidlDisplayName(CSIDL_DRIVES, computerPath, SIZEOF_ARRAY(computerPath), SHGDN_FORPARSING);
		return computerPath;
	}
};