// Copyright (C) Explorer++ Project
// SPDX-License-Identifier: GPL-3.0-only
// See LICENSE in the top level directory

#pragma once

#include "IconMapping.h"

const IconMapping ICON_RESOURCE_MAPPINGS_WINDOWS_10 = {
	{ Icon::AddBookmark, { ICON_SIZE_MAPPINGS(IDB_ADD_BOOKMARK_WINDOWS_10) } },
	{ Icon::ArrowRight, { ICON_SIZE_MAPPINGS(IDB_ARROW_RIGHT_WINDOWS_10) } },
	{ Icon::Back, { ICON_SIZE_MAPPINGS(IDB_BACK_WINDOWS_10) } },
	{ Icon::Bookmarks, { ICON_SIZE_MAPPINGS(IDB_BOOKMARKS_WINDOWS_10) } },
	{ Icon::CloseButton, { ICON_SIZE_MAPPINGS(IDB_CLOSE_BUTTON_WINDOWS_10) } },
	{ Icon::CloseTab, { ICON_SIZE_MAPPINGS(IDB_CLOSE_TAB_WINDOWS_10) } },
	{ Icon::CommandLine, { ICON_SIZE_MAPPINGS(IDB_COMMAND_LINE_WINDOWS_10) } },
	{ Icon::CommandLineAdmin, { ICON_SIZE_MAPPINGS(IDB_COMMAND_LINE_ADMIN_WINDOWS_10) } },
	{ Icon::Copy, { ICON_SIZE_MAPPINGS(IDB_COPY_WINDOWS_10) } },
	{ Icon::CopyTo, { ICON_SIZE_MAPPINGS(IDB_COPY_TO_WINDOWS_10) } },
	{ Icon::CustomizeColors, { ICON_SIZE_MAPPINGS(IDB_CUSTOMIZE_COLORS_WINDOWS_10) } },
	{ Icon::Cut, { ICON_SIZE_MAPPINGS(IDB_CUT_WINDOWS_10) } },
	{ Icon::Delete, { ICON_SIZE_MAPPINGS(IDB_DELETE_WINDOWS_10) } },
	{ Icon::DeletePermanently, { ICON_SIZE_MAPPINGS(IDB_DELETE_PERMANENTLY_WINDOWS_10) } },
	{ Icon::Filter, { ICON_SIZE_MAPPINGS(IDB_FILTER_WINDOWS_10) } },
	{ Icon::Folder, { ICON_SIZE_MAPPINGS(IDB_FOLDER_WINDOWS_10) } },
	{ Icon::FolderTree, { ICON_SIZE_MAPPINGS(IDB_FOLDER_TREE_WINDOWS_10) } },
	{ Icon::Forward, { ICON_SIZE_MAPPINGS(IDB_FORWARD_WINDOWS_10) } },
	{ Icon::Help, { ICON_SIZE_MAPPINGS(IDB_HELP_WINDOWS_10) } },
	{ Icon::Lock, { ICON_SIZE_MAPPINGS(IDB_LOCK_WINDOWS_10) } },
	{ Icon::MassRename, { ICON_SIZE_MAPPINGS(IDB_MASS_RENAME_WINDOWS_10) } },
	{ Icon::MergeFiles, { ICON_SIZE_MAPPINGS(IDB_MERGE_FILES_WINDOWS_10) } },
	{ Icon::MoveTo, { ICON_SIZE_MAPPINGS(IDB_MOVE_TO_WINDOWS_10) } },
	{ Icon::NewFolder, { ICON_SIZE_MAPPINGS(IDB_NEW_FOLDER_WINDOWS_10) } },
	{ Icon::NewTab, { ICON_SIZE_MAPPINGS(IDB_NEW_TAB_WINDOWS_10) } },
	{ Icon::Options, { ICON_SIZE_MAPPINGS(IDB_OPTIONS_WINDOWS_10) } },
	{ Icon::Paste, { ICON_SIZE_MAPPINGS(IDB_PASTE_WINDOWS_10) } },
	{ Icon::PasteShortcut, { ICON_SIZE_MAPPINGS(IDB_PASTE_SHORTCUT_WINDOWS_10) } },
	{ Icon::Properties, { ICON_SIZE_MAPPINGS(IDB_PROPERTIES_WINDOWS_10) } },
	{ Icon::Refresh, { ICON_SIZE_MAPPINGS(IDB_REFRESH_WINDOWS_10) } },
	{ Icon::Rename, { ICON_SIZE_MAPPINGS(IDB_RENAME_WINDOWS_10) } },
	{ Icon::Search, { ICON_SIZE_MAPPINGS(IDB_SEARCH_WINDOWS_10) } },
	{ Icon::SelectColumns, { ICON_SIZE_MAPPINGS(IDB_SELECT_COLUMNS_WINDOWS_10) } },
	{ Icon::SplitFiles, { ICON_SIZE_MAPPINGS(IDB_SPLIT_FILES_WINDOWS_10) } },
	{ Icon::Undo, { ICON_SIZE_MAPPINGS(IDB_UNDO_WINDOWS_10) } },
	{ Icon::Up, { ICON_SIZE_MAPPINGS(IDB_UP_WINDOWS_10) } },
	{ Icon::Views, { ICON_SIZE_MAPPINGS(IDB_VIEWS_WINDOWS_10) } }
};