// Copyright (C) Explorer++ Project
// SPDX-License-Identifier: GPL-3.0-only
// See LICENSE in the top level directory

#pragma once

#define MENU_BOOKMARK_START_ID 10000
#define MENU_BOOKMARK_END_ID 11000
#define MENU_RECENT_TABS_START_ID 12000
#define MENU_RECENT_TABS_END_ID 13000
#define MENU_PLUGIN_START_ID 14000
#define MENU_PLUGIN_END_ID 15000
#define ACCELERATOR_PLUGIN_START_ID 16000
#define ACCELERATOR_PLUGIN_END_ID 17000
#define MENU_GLOBAL_HISTORY_START_ID 18000
#define MENU_GLOBAL_HISTORY_END_ID 19000
