// Copyright (C) Explorer++ Project
// SPDX-License-Identifier: GPL-3.0-only
// See LICENSE in the top level directory

#pragma once

// Note that these values are used to save the toolbar state and should not be
// changed.
#define TOOLBAR_ID_START			45000
#define TOOLBAR_SEPARATOR			(TOOLBAR_ID_START + 1)
#define TOOLBAR_BACK				(TOOLBAR_ID_START + 2)
#define TOOLBAR_FORWARD				(TOOLBAR_ID_START + 3)
#define TOOLBAR_UP					(TOOLBAR_ID_START + 4)
#define TOOLBAR_FOLDERS				(TOOLBAR_ID_START + 5)
#define TOOLBAR_COPY_TO				(TOOLBAR_ID_START + 6)
#define TOOLBAR_MOVE_TO				(TOOLBAR_ID_START + 7)
#define TOOLBAR_NEW_FOLDER			(TOOLBAR_ID_START + 8)
#define TOOLBAR_COPY				(TOOLBAR_ID_START + 9)
#define TOOLBAR_CUT					(TOOLBAR_ID_START + 10)
#define TOOLBAR_PASTE				(TOOLBAR_ID_START + 11)
#define TOOLBAR_DELETE				(TOOLBAR_ID_START + 12)
#define TOOLBAR_VIEWS				(TOOLBAR_ID_START + 13)
#define TOOLBAR_SEARCH				(TOOLBAR_ID_START + 14)
#define TOOLBAR_PROPERTIES			(TOOLBAR_ID_START + 15)
#define TOOLBAR_REFRESH				(TOOLBAR_ID_START + 17)
#define TOOLBAR_ADD_BOOKMARK		(TOOLBAR_ID_START + 18)
#define TOOLBAR_NEW_TAB				(TOOLBAR_ID_START + 19)
#define TOOLBAR_OPEN_COMMAND_PROMPT	(TOOLBAR_ID_START + 20)
#define TOOLBAR_ORGANIZE_BOOKMARKS	(TOOLBAR_ID_START + 21)
#define TOOLBAR_DELETE_PERMANENTLY	(TOOLBAR_ID_START + 22)
#define TOOLBAR_SPLIT_FILE			(TOOLBAR_ID_START + 23)
#define TOOLBAR_MERGE_FILES			(TOOLBAR_ID_START + 24)

/* This represents the total set of buttons. */
static const int TOOLBAR_BUTTON_SET[] = {
	TOOLBAR_BACK,
	TOOLBAR_FORWARD,
	TOOLBAR_UP,
	TOOLBAR_FOLDERS,
	TOOLBAR_COPY_TO,
	TOOLBAR_MOVE_TO,
	TOOLBAR_NEW_FOLDER,
	TOOLBAR_COPY,
	TOOLBAR_CUT,
	TOOLBAR_PASTE,
	TOOLBAR_DELETE,
	TOOLBAR_VIEWS,
	TOOLBAR_SEARCH,
	TOOLBAR_PROPERTIES,
	TOOLBAR_REFRESH,
	TOOLBAR_ADD_BOOKMARK,
	TOOLBAR_NEW_TAB,
	TOOLBAR_OPEN_COMMAND_PROMPT,
	TOOLBAR_ORGANIZE_BOOKMARKS,
	TOOLBAR_DELETE_PERMANENTLY,
	TOOLBAR_SPLIT_FILE,
	TOOLBAR_MERGE_FILES
};