//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShellBrowser.rc
//
#define IDB_BITMAP2                     102
#define IDB_BITMAP1                     104
#define IDS_COLUMN_DESCRIPTION_NAME     2000
#define IDS_COLUMN_DESCRIPTION_TYPE     2001
#define IDS_COLUMN_DESCRIPTION_SIZE     2002
#define IDS_COLUMN_DESCRIPTION_MODIFIED 2003
#define IDS_COLUMN_DESCRIPTION_ATTRIBUTES 2004
#define IDS_COLUMN_DESCRIPTION_REALSIZE 2005
#define IDS_COLUMN_DESCRIPTION_SHORTNAME 2006
#define IDS_COLUMN_DESCRIPTION_OWNER    2007
#define IDS_COLUMN_DESCRIPTION_PRODUCTNAME 2008
#define IDS_COLUMN_DESCRIPTION_COMPANY  2009
#define IDS_COLUMN_DESCRIPTION_DESCRIPTION 2010
#define IDS_COLUMN_DESCRIPTION_FILEVERSION 2011
#define IDS_COLUMN_DESCRIPTION_PRODUCTVERSION 2012
#define IDS_COLUMN_DESCRIPTION_SHORTCUTTO 2013
#define IDS_COLUMN_DESCRIPTION_HARDLINKS 2014
#define IDS_COLUMN_DESCRIPTION_EXTENSION 2015
#define IDS_COLUMN_DESCRIPTION_CREATED  2016
#define IDS_COLUMN_DESCRIPTION_ACCESSED 2017
#define IDS_COLUMN_DESCRIPTION_TITLE    2018
#define IDS_COLUMN_DESCRIPTION_SUBJECT  2019
#define IDS_COLUMN_DESCRIPTION_AUTHOR   2020
#define IDS_COLUMN_DESCRIPTION_KEYWORDS 2021
#define IDS_COLUMN_DESCRIPTION_COMMENT  2022
#define IDS_COLUMN_DESCRIPTION_CAMERAMODEL 2023
#define IDS_COLUMN_DESCRIPTION_DATETAKEN 2024
#define IDS_COLUMN_DESCRIPTION_WIDTH    2025
#define IDS_COLUMN_DESCRIPTION_HEIGHT   2026
#define IDS_COLUMN_DESCRIPTION_TOTALSIZE 2027
#define IDS_COLUMN_DESCRIPTION_FREESPACE 2028
#define IDS_COLUMN_DESCRIPTION_FILESYSTEM 2029
#define IDS_COLUMN_DESCRIPTION_NUMPRINTERDOCUMENTS 2030
#define IDS_COLUMN_DESCRIPTION_PRINTERCOMMENTS 2031
#define IDS_COLUMN_DESCRIPTION_PRINTERLOCATION 2032
#define IDS_COLUMN_DESCRIPTION_NETWORKADAPTER_STATUS 2033
#define IDS_NETWORKADAPTER_CONNECTED    2034
#define IDS_NETWORKADAPTER_DISCONNECTED 2035
#define IDS_NETWORKADAPTER_TESTING      2036
#define IDS_NETWORKADAPTER_UNKNOWN      2037
#define IDS_NETWORKADAPTER_DORMANT      2038
#define IDS_NETWORKADAPTER_NOTPRESENT   2039
#define IDS_NETWORKADAPTER_LOWLAYER     2040
#define IDS_SELECTCOLUMNSDLG_OK         2041
#define IDS_SELECTCOLUMNSDLG_CANCEL     2042
#define IDS_SELECTCOLUMNSDLG_MOVEUP     2043
#define IDS_SELECTCOLUMNSDLG_MOVEDOWN   2044
#define IDS_SELECTCOLUMNSDLG_ENABLE     2045
#define IDS_SELECTCOLUMNSDLG_DISABLE    2046
#define IDS_SELECTCOLUMNSDLG_DESCRIPTION 2047
#define IDS_SELECTCOLUMNSDLG_COLUMNS    2048
#define IDS_COLUMN_NAME_NAME            2049
#define IDS_COLUMN_NAME_TYPE            2050
#define IDS_COLUMN_NAME_SIZE            2051
#define IDS_COLUMN_NAME_DATEMODIFIED    2052
#define IDS_COLUMN_NAME_ATTRIBUTES      2053
#define IDS_COLUMN_NAME_REALSIZE        2054
#define IDS_COLUMN_NAME_SHORTNAME       2055
#define IDS_COLUMN_NAME_OWNER           2056
#define IDS_COLUMN_NAME_PRODUCTNAME     2057
#define IDS_COLUMN_NAME_COMPANY         2058
#define IDS_COLUMN_NAME_DESCRIPTION     2059
#define IDS_COLUMN_NAME_FILEVERSION     2060
#define IDS_COLUMN_NAME_PRODUCTVERSION  2061
#define IDS_COLUMN_NAME_SHORTCUTTO      2062
#define IDS_COLUMN_NAME_HARDLINKS       2063
#define IDS_COLUMN_NAME_EXTENSION       2064
#define IDS_COLUMN_NAME_CREATED         2065
#define IDS_COLUMN_NAME_ACCESSED        2066
#define IDS_COLUMN_NAME_TITLE           2067
#define IDS_COLUMN_NAME_SUBJECT         2068
#define IDS_COLUMN_NAME_AUTHOR          2069
#define IDS_COLUMN_NAME_KEYWORDS        2070
#define IDS_COLUMN_NAME_COMMENT         2071
#define IDS_COLUMN_NAME_CAMERAMODEL     2072
#define IDS_COLUMN_NAME_DATETAKEN       2073
#define IDS_COLUMN_NAME_WIDTH           2074
#define IDS_COLUMN_NAME_HEIGHT          2075
#define IDS_COLUMN_NAME_VIRTUALCOMMENTS 2076
#define IDS_COLUMN_NAME_TOTALSIZE       2077
#define IDS_COLUMN_NAME_FREESPACE       2078
#define IDS_COLUMN_NAME_FILESYSTEM      2079
#define IDS_COLUMN_NAME_VIRTUALTYPE     2080
#define IDS_COLUMN_NAME_ORIGINALLOCATION 2081
#define IDS_COLUMN_NAME_DATEDELETED     2082
#define IDS_COLUMN_NAME_NUMPRINTERDOCUMENTS 2083
#define IDS_COLUMN_NAME_PRINTERSTATUS   2084
#define IDS_COLUMN_NAME_PRINTERCOMMENTS 2085
#define IDS_COLUMN_NAME_PRINTERLOCATION 2086
#define IDS_COLUMN_NAME_NETWORKADAPTER_STATUS 2087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
