name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  EXPLORERPLUSPLUS_BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    name: ${{ matrix.configuration }} / ${{ matrix.platform }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - configuration: Debug-Asan
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: false

          - configuration: Release-Clang
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: false

          - configuration: Release
            platform: Win32
            runner: windows-2022
            msbuild-architecture: x64
            publish: true

          - configuration: Release
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: true

          - configuration: Release
            platform: ARM64
            runner: windows-11-arm
            msbuild-architecture: arm64
            publish: true

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3
        with:
          msbuild-architecture: ${{ matrix.msbuild-architecture }}

      - name: Cache vcpkg binary packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-${{ matrix.configuration }}-${{ matrix.platform }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      - name: Bootstrap vcpkg
        run: Explorer++/ThirdParty/vcpkg/bootstrap-vcpkg.bat

      - name: Build
        run: msbuild Explorer++/Explorer++.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /v:minimal

      - name: Run tests
        run: ./.github/run_tests.ps1 -Configuration '${{ matrix.configuration }}' -Platform '${{ matrix.platform }}'

      - name: Package artifacts
        if: matrix.publish
        run: ./.github/package.ps1 -Configuration '${{ matrix.configuration }}' -Platform '${{ matrix.platform }}'

      - name: Upload artifacts
        if: matrix.publish
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Explorer++.${{ matrix.configuration }}.${{ matrix.platform }}
          path: artifacts
          if-no-files-found: error
          compression-level: 0
