name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: {}

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && format('{0}-{1}', github.workflow, github.ref) || github.run_id }}

jobs:
  before-build:
    name: Before build
    runs-on: ubuntu-slim

    outputs:
      deployment-environment: ${{ steps.classify.outputs.environment }}
      build-number: ${{ steps.build-number.outputs.build-number }}

    steps:
      # This classifies the build type for deployment. When set, it indicates that a deployment will take place. This
      # won't be set for unofficial builds (e.g. pull request builds).
      - name: Classify build type
        id: classify
        shell: pwsh
        run: |
          $environment = switch -Regex ('${{ github.ref }}') {
            '^refs/heads/master$' {
              'dev'
              break
            }

            default {
              ''
            }
          }

          "environment=$environment" >> $env:GITHUB_OUTPUT

      # Note that the offset below brings the build number in line with the previous AppVeyor build number. Unofficial
      # builds always use a build number of 0.
      - name: Calculate build number
        id: build-number
        shell: pwsh
        env:
          DEPLOYMENT_ENVIRONMENT: ${{ steps.classify.outputs.environment }}
        run: |
          if ($env:DEPLOYMENT_ENVIRONMENT) {
            $buildNumber = [int] $env:GITHUB_RUN_NUMBER + 2809
          } else {
            $buildNumber = 0
          }

          "build-number=$buildNumber" >> $env:GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.configuration }} / ${{ matrix.platform }}
    needs: before-build

    permissions:
      attestations: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false

      matrix:
        include:
          - configuration: Debug-Asan
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: false

          - configuration: Release-Clang
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: false

          - configuration: Release
            platform: Win32
            runner: windows-2022
            msbuild-architecture: x64
            publish: true

          - configuration: Release
            platform: x64
            runner: windows-2022
            msbuild-architecture: x64
            publish: true

          - configuration: Release
            platform: ARM64
            runner: windows-11-arm
            msbuild-architecture: arm64
            publish: true

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3
        with:
          msbuild-architecture: ${{ matrix.msbuild-architecture }}

      - name: Cache vcpkg binary packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-${{ matrix.configuration }}-${{ matrix.platform }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      - name: Bootstrap vcpkg
        run: Explorer++/ThirdParty/vcpkg/bootstrap-vcpkg.bat

      - name: Build
        run: |
          msbuild `
            Explorer++/Explorer++.sln `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=${{ matrix.platform }} `
            /p:ExplorerPlusPlusBuildVersion=${{ needs.before-build.outputs.build-number }} `
            /v:minimal

      - name: Run tests
        run: ./.github/run_tests.ps1 -Configuration '${{ matrix.configuration }}' -Platform '${{ matrix.platform }}'

      - name: Package artifacts
        if: matrix.publish
        run: ./.github/package.ps1 -Configuration '${{ matrix.configuration }}' -Platform '${{ matrix.platform }}'

      - name: Attest artifacts
        if: matrix.publish && needs.before-build.outputs.deployment-environment != ''
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: 'artifacts/*'

      - name: Upload artifacts
        if: matrix.publish
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Explorer++.${{ matrix.configuration }}.${{ matrix.platform }}
          path: artifacts
          if-no-files-found: error
          compression-level: 0

  deploy:
    name: Deploy
    needs:
      - before-build
      - build
    if: needs.before-build.outputs.deployment-environment != ''
    runs-on: ubuntu-latest

    environment:
      name: ${{ needs.before-build.outputs.deployment-environment }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: deployment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy
        shell: pwsh
        run: |
          ./.github/deploy.ps1 `
            -DeploymentDirectory deployment `
            -BucketPathPrefix '${{ vars.S3_PREFIX }}' `
            -BuildNumber '${{ needs.before-build.outputs.build-number }}'
